# Generated by Django 3.2.8 on 2021-10-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
