# Generated by Django 3.2.8 on 2021-10-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_address_pin"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection (title)
            VALUES ('first_collection')
        """,
            """
            DELETE FROM store_collection
            where title='first_collection'
        """,
        )
    ]
